export interface SendMessageParams {
  message: string;
  sessionId?: string;
  chatId: string;
  systemPrompt?: string;
  onTyping?: () => void;
  allowedTools?: string[];
  modelOverride?: string;
  images?: string[];
  /** Force chat-only mode (skip tool routing). Use for pre-parsed content like uploaded documents. */
  skipTools?: boolean;
  /** When true, the message originated from a voice note — triggers concise conversational replies. */
  isVoice?: boolean;
  /** When true, skip skill auto-triggering for this message (used by orchestrator step calls). */
  skipAutoTrigger?: boolean;
  /** Platform the message originated from — used for provider-aware identity in system prompt. */
  platform?: 'telegram' | 'matrix' | 'voice-web';
  /**
   * Extra system-prompt fragment appended (not replacing) the regular one.
   * For Claude this maps to `--append-system-prompt`; for Ollama it is
   * concatenated onto the system message. Used by the router to inject
   * a cross-provider conversation recap when the active provider just
   * changed (rc.69 continuity bridge).
   */
  systemPromptAppend?: string;
  /**
   * The clean user text, before platform-level enrichment (memory
   * prefixes, retrieved-context blocks, etc). When provided, the
   * router uses this for chat_log storage so the continuity bridge
   * seeds downstream providers with the user's actual words — not
   * with their in-prompt retrieval envelope. Falls back to `message`
   * when not set (rc.70).
   */
  rawUserMessage?: string;
  /**
   * When true, the router skips both the continuity-bridge seed and
   * the chat_log append for this call. Internal LLM invocations
   * (auto-skill drafter, scheduler follow-ups, orchestrator step
   * expansion) must set this — their prompts are NOT conversation
   * turns and must not pollute the turn log (rc.70).
   */
  skipTurnLog?: boolean;
  /**
   * ISO-639-1 language hint ('en' or 'es') derived from a reliable source
   * (e.g. Whisper STT auto-detection). When set, overrides the router's
   * stopword-based heuristic — STT on a full utterance is more accurate
   * than stopword counts on a short text, and short utterances like
   * "okay" / "continue" otherwise fall back to 'unknown' and let the
   * prior turn's language inertia win (rc.82).
   */
  languageHint?: 'en' | 'es';
  /**
   * When true, `systemPrompt` is already a complete, self-contained system
   * prompt (the router's Task 4 local assembler for the Ollama path) rather
   * than a fragment meant to be layered on top of a provider's own base
   * persona. Ollama's agentic loop uses this to skip prepending its fat
   * TOOL_MODEL_SYSTEM_PROMPT persona, avoiding duplication (pipeline surgery
   * Task 5). Non-router callers (e.g. voice) omit this and keep today's
   * un-assembled behavior.
   */
  assembledSystemPrompt?: boolean;
}

export interface GeneratedFile {
  path: string;
  filename: string;
  mimeType: string;
}

export interface AIResponse {
  text: string | null;
  newSessionId?: string;
  provider: 'claude' | 'ollama';
  model?: string;
  thinkingContent?: string;
  /** Set when Claude CLI reports a stale/missing session ID */
  staleSession?: boolean;
  /** Files generated by tool calls (e.g. generate_document) */
  generatedFiles?: GeneratedFile[];
  /** Notification message when a skill was auto-triggered for this message */
  autoTriggerNotice?: string;
  /** Tool names used during this response (tracked in Ollama agentic loop) */
  toolsUsed?: string[];
  /**
   * Set when the Ollama agentic loop exhausted MAX_ITERATIONS without
   * producing a no-tool-calls final response. Signals a failed workflow
   * — callers should NOT treat this as skill-worthy or high-quality.
   */
  hitMaxIterations?: boolean;
  /**
   * Count of tool calls that returned an error during this response.
   * Used by auto-skill detection to avoid proposing skills based on
   * failed workflows.
   */
  toolErrorCount?: number;
}

export interface AIProvider {
  name: 'claude' | 'ollama';
  sendMessage(params: SendMessageParams): Promise<AIResponse>;
}
