export interface SendMessageParams {
  message: string;
  sessionId?: string;
  chatId: string;
  systemPrompt?: string;
  onTyping?: () => void;
  allowedTools?: string[];
  modelOverride?: string;
  images?: string[];
  /** Force chat-only mode (skip tool routing). Use for pre-parsed content like uploaded documents. */
  skipTools?: boolean;
  /** When true, the message originated from a voice note — triggers concise conversational replies. */
  isVoice?: boolean;
  /** When true, skip skill auto-triggering for this message (used by orchestrator step calls). */
  skipAutoTrigger?: boolean;
}

export interface GeneratedFile {
  path: string;
  filename: string;
  mimeType: string;
}

export interface AIResponse {
  text: string | null;
  newSessionId?: string;
  provider: 'claude' | 'ollama';
  model?: string;
  thinkingContent?: string;
  /** Set when Claude CLI reports a stale/missing session ID */
  staleSession?: boolean;
  /** Files generated by tool calls (e.g. generate_document) */
  generatedFiles?: GeneratedFile[];
  /** Notification message when a skill was auto-triggered for this message */
  autoTriggerNotice?: string;
}

export interface AIProvider {
  name: 'claude' | 'ollama';
  sendMessage(params: SendMessageParams): Promise<AIResponse>;
}
