export interface SendMessageParams {
  message: string;
  sessionId?: string;
  chatId: string;
  systemPrompt?: string;
  onTyping?: () => void;
  allowedTools?: string[];
  modelOverride?: string;
  images?: string[];
  /** Force chat-only mode (skip tool routing). Use for pre-parsed content like uploaded documents. */
  skipTools?: boolean;
  /** When true, the message originated from a voice note — triggers concise conversational replies. */
  isVoice?: boolean;
  /** When true, skip skill auto-triggering for this message (used by orchestrator step calls). */
  skipAutoTrigger?: boolean;
  /** Platform the message originated from — used for provider-aware identity in system prompt. */
  platform?: 'telegram' | 'matrix' | 'voice-web';
  /**
   * Extra system-prompt fragment appended (not replacing) the regular one.
   * For Claude this maps to `--append-system-prompt`; for Ollama it is
   * concatenated onto the system message. Used by the router to inject
   * a cross-provider conversation recap when the active provider just
   * changed (rc.69 continuity bridge).
   */
  systemPromptAppend?: string;
}

export interface GeneratedFile {
  path: string;
  filename: string;
  mimeType: string;
}

export interface AIResponse {
  text: string | null;
  newSessionId?: string;
  provider: 'claude' | 'ollama';
  model?: string;
  thinkingContent?: string;
  /** Set when Claude CLI reports a stale/missing session ID */
  staleSession?: boolean;
  /** Files generated by tool calls (e.g. generate_document) */
  generatedFiles?: GeneratedFile[];
  /** Notification message when a skill was auto-triggered for this message */
  autoTriggerNotice?: string;
  /** Tool names used during this response (tracked in Ollama agentic loop) */
  toolsUsed?: string[];
}

export interface AIProvider {
  name: 'claude' | 'ollama';
  sendMessage(params: SendMessageParams): Promise<AIResponse>;
}
