/**
 * FSM Code Generation — PLC Structured Text (IEC 61131-3)
 *
 * Exports an FSM definition as Structured Text suitable for
 * PLC programming environments (Siemens TIA Portal, Codesys, etc.).
 */

import type { FSMDefinition } from './models.js';

/**
 * Generate IEC 61131-3 Structured Text from an FSM definition.
 * Produces a FUNCTION_BLOCK with state enum, CASE-based transition logic,
 * and entry/exit actions.
 */
export function generateStructuredText(fsm: FSMDefinition): string {
  const blockName = sanitizeName(fsm.name);
  const states = fsm.states;
  const transitions = fsm.transitions;
  const initial = states.find((s) => s.is_initial) ?? states[0];

  const lines: string[] = [];

  // Header
  lines.push(`(* ============================================== *)`);
  lines.push(`(* FSM: ${fsm.name} *)`);
  lines.push(`(* Generated by clauded State Machine Simulator *)`);
  lines.push(`(* IEC 61131-3 Structured Text *)`);
  lines.push(`(* ============================================== *)`);
  lines.push('');

  // State enum type
  lines.push(`TYPE E_${blockName}_State :`);
  lines.push(`(`);
  for (let i = 0; i < states.length; i++) {
    const comma = i < states.length - 1 ? ',' : '';
    lines.push(`    ${sanitizeName(states[i].name)} := ${i}${comma}    (* ${states[i].mfg_type} *)`);
  }
  lines.push(`);`);
  lines.push(`END_TYPE`);
  lines.push('');

  // Function block
  lines.push(`FUNCTION_BLOCK FB_${blockName}`);
  lines.push('');

  // VAR_INPUT — events as BOOL triggers
  lines.push(`VAR_INPUT`);
  const uniqueEvents = Array.from(new Set(transitions.map((t) => t.event)));
  for (const evt of uniqueEvents) {
    lines.push(`    ${sanitizeName(evt)} : BOOL;    (* Event trigger *)`);
  }
  // Guard inputs
  const uniqueGuards = Array.from(new Set(
    transitions.filter((t) => t.guard).map((t) => extractGuardVars(t.guard!)),
  )).flat();
  const guardVars = Array.from(new Set(uniqueGuards));
  for (const gv of guardVars) {
    lines.push(`    ${sanitizeName(gv)} : BOOL;    (* Guard condition *)`);
  }
  lines.push(`END_VAR`);
  lines.push('');

  // VAR_OUTPUT
  lines.push(`VAR_OUTPUT`);
  lines.push(`    CurrentState : E_${blockName}_State;`);
  lines.push(`    StateChanged : BOOL;`);
  lines.push(`END_VAR`);
  lines.push('');

  // VAR — internal
  lines.push(`VAR`);
  lines.push(`    PrevState : E_${blockName}_State;`);
  lines.push(`END_VAR`);
  lines.push('');

  // Initialization
  if (initial) {
    lines.push(`(* Initialize to ${initial.name} *)`);
    lines.push(`IF CurrentState = 0 AND PrevState = 0 THEN`);
    lines.push(`    CurrentState := E_${blockName}_State#${sanitizeName(initial.name)};`);
    lines.push(`END_IF;`);
    lines.push('');
  }

  // State tracking
  lines.push(`PrevState := CurrentState;`);
  lines.push(`StateChanged := FALSE;`);
  lines.push('');

  // CASE statement for transitions
  lines.push(`CASE CurrentState OF`);

  for (const state of states) {
    const stateTransitions = transitions.filter((t) => t.from_state_id === state.id);
    if (stateTransitions.length === 0 && state.is_final) {
      lines.push(`    E_${blockName}_State#${sanitizeName(state.name)}:`);
      lines.push(`        ; (* Final state — no transitions *)`);
      lines.push('');
      continue;
    }

    lines.push(`    E_${blockName}_State#${sanitizeName(state.name)}:`);

    // Entry action comment
    if (state.entry_action) {
      lines.push(`        (* Entry: ${state.entry_action} *)`);
    }

    for (const t of stateTransitions) {
      const toState = states.find((s) => s.id === t.to_state_id);
      if (!toState) continue;

      let condition = sanitizeName(t.event);
      if (t.guard) {
        condition += ` AND (${convertGuardToST(t.guard)})`;
      }

      lines.push(`        IF ${condition} THEN`);
      if (state.exit_action) {
        lines.push(`            (* Exit: ${state.exit_action} *)`);
      }
      if (t.action) {
        lines.push(`            (* Action: ${t.action} *)`);
      }
      lines.push(`            CurrentState := E_${blockName}_State#${sanitizeName(toState.name)};`);
      lines.push(`            StateChanged := TRUE;`);
      lines.push(`        END_IF;`);
    }
    lines.push('');
  }

  lines.push(`END_CASE;`);
  lines.push('');
  lines.push(`END_FUNCTION_BLOCK`);

  return lines.join('\n');
}

// ── Helpers ──────────────────────────────────────────────────

function sanitizeName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^(\d)/, '_$1')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '') || 'unnamed';
}

function extractGuardVars(guard: string): string[] {
  // Extract variable names from guard expressions
  return guard
    .replace(/&&|\|\||!|[<>=]+|\d+\.?\d*/g, ' ')
    .split(/\s+/)
    .filter((v) => v.length > 0 && !/^\d/.test(v));
}

function convertGuardToST(guard: string): string {
  return guard
    .replace(/&&/g, ' AND ')
    .replace(/\|\|/g, ' OR ')
    .replace(/!/g, 'NOT ')
    .replace(/==/g, '=')
    .split(/\s+/)
    .map((token) => /^[a-zA-Z]/.test(token) ? sanitizeName(token) : token)
    .join(' ');
}
