#!/usr/bin/env tsx
/**
 * Interactive setup wizard for Luna.
 *
 * Usage: npx tsx scripts/setup.ts
 *
 * Steps:
 * 1. Check requirements (Node >=26, claude CLI, Docker, Ollama)
 * 2. Collect: Telegram bot token, chat ID, AI provider
 * 3. Open LUNA.md in $EDITOR for personalization
 * 4. Write .env
 * 5. Build the project
 * 6. Install background service (launchd/systemd)
 * 7. Print next steps
 */

import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { platform } from 'node:os';
import { createInterface } from 'node:readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = resolve(__dirname, '..');

const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const BOLD = '\x1b[1m';
const RESET = '\x1b[0m';

function pass(msg: string): void {
  console.log(`  ${GREEN}✓${RESET} ${msg}`);
}
function warn(msg: string): void {
  console.log(`  ${YELLOW}⚠${RESET} ${msg}`);
}
function fail(msg: string): void {
  console.log(`  ${RED}✗${RESET} ${msg}`);
}

function tryExec(cmd: string): string | null {
  try {
    return execSync(cmd, { encoding: 'utf-8', timeout: 10_000, stdio: 'pipe' }).trim();
  } catch {
    return null;
  }
}

const rl = createInterface({ input: process.stdin, output: process.stdout });
function ask(question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(`  ${question}: `, (answer) => resolve(answer.trim()));
  });
}

async function main(): Promise<void> {
  // Show banner
  const bannerPath = resolve(PROJECT_ROOT, 'banner.txt');
  if (existsSync(bannerPath)) {
    console.log(readFileSync(bannerPath, 'utf-8'));
  }
  console.log(`${BOLD}=== Luna Setup Wizard ===${RESET}\n`);

  // ── Step 1: Check requirements ────────────────────────────

  console.log(`${BOLD}Step 1: Checking requirements${RESET}\n`);

  let hasErrors = false;

  const nodeVersion = parseInt(process.version.slice(1));
  if (nodeVersion >= 26) {
    pass(`Node.js ${process.version}`);
  } else {
    fail(`Node.js ${process.version} — requires >= 26`);
    hasErrors = true;
  }

  const claudeCli = tryExec('claude --version');
  if (claudeCli) {
    pass(`Claude CLI: ${claudeCli}`);
  } else {
    warn('Claude CLI not found — install with: npm i -g @anthropic-ai/claude-code');
  }

  const docker = tryExec('docker --version');
  if (docker) {
    pass('Docker installed');
  } else {
    warn('Docker not found — needed for sandboxing and voice');
  }

  const ollama = tryExec('ollama --version');
  if (ollama) {
    pass('Ollama installed');
  } else {
    warn('Ollama not found — needed for the Ollama AI provider');
  }

  if (hasErrors) {
    console.log(`\n${RED}Fix the errors above before continuing.${RESET}`);
    rl.close();
    process.exit(1);
  }

  // ── Step 2: Collect configuration ─────────────────────────

  console.log(`\n${BOLD}Step 2: Configuration${RESET}\n`);

  const aiProvider = (await ask('Default AI provider (claude/ollama) [claude]')) || 'claude';
  const telegramToken = await ask('Telegram bot token (from @BotFather)');
  const chatId = await ask('Your Telegram chat ID (send /chatid to your bot, or leave blank)');

  const wantMatrix = (await ask('Set up Matrix? (y/n) [n]')).toLowerCase() === 'y';
  let matrixHomeserver = '';
  let matrixToken = '';
  if (wantMatrix) {
    matrixHomeserver = (await ask('Matrix homeserver URL [http://localhost:8008]')) || 'http://localhost:8008';
    matrixToken = await ask('Matrix access token (run scripts/setup-matrix.ts first, or leave blank)');
  }

  // ── Step 3: Open LUNA.md for personalization ───────────

  console.log(`\n${BOLD}Step 3: Personalization${RESET}\n`);
  const editor = process.env.EDITOR || process.env.VISUAL;
  const lunaMdPath = resolve(PROJECT_ROOT, 'LUNA.md');
  if (editor && existsSync(lunaMdPath)) {
    console.log(`  Opening LUNA.md in ${editor} for personalization...`);
    console.log('  Edit the "Personalization" section, then save and close.\n');
    try {
      execSync(`${editor} "${lunaMdPath}"`, { stdio: 'inherit' });
      pass('LUNA.md personalized');
    } catch {
      warn('Could not open editor — edit LUNA.md manually later');
    }
  } else {
    warn('No $EDITOR set — edit LUNA.md manually later');
  }

  // ── Step 4: Write .env ────────────────────────────────────

  console.log(`\n${BOLD}Step 4: Writing .env${RESET}\n`);

  const envContent = [
    '# Luna — Generated by setup wizard',
    `AI_PROVIDER=${aiProvider}`,
    '',
    `TELEGRAM_BOT_TOKEN=${telegramToken}`,
    `ALLOWED_CHAT_ID=${chatId}`,
    '',
    `OLLAMA_HOST=http://localhost:11434`,
    `OLLAMA_CHAT_MODEL=bazobehram/qwen3-14b-claude-4.5-opus-high-reasoning`,
    `OLLAMA_TOOL_MODEL=qwen3:14b`,
    '',
    `SPEACHES_URL=http://localhost:8000/v1`,
    '',
    wantMatrix ? `MATRIX_HOMESERVER=${matrixHomeserver}` : '# MATRIX_HOMESERVER=http://localhost:8008',
    wantMatrix ? `MATRIX_ACCESS_TOKEN=${matrixToken}` : '# MATRIX_ACCESS_TOKEN=',
    '',
    'LOG_LEVEL=info',
  ].join('\n');

  const envPath = resolve(PROJECT_ROOT, '.env');
  if (existsSync(envPath)) {
    const overwrite = (await ask('.env already exists. Overwrite? (y/n) [n]')).toLowerCase();
    if (overwrite !== 'y') {
      warn('Keeping existing .env');
    } else {
      writeFileSync(envPath, envContent + '\n');
      pass('.env written');
    }
  } else {
    writeFileSync(envPath, envContent + '\n');
    pass('.env written');
  }

  // ── Step 5: Build ─────────────────────────────────────────

  console.log(`\n${BOLD}Step 5: Building project${RESET}\n`);
  try {
    execSync('npm run build', { cwd: PROJECT_ROOT, stdio: 'inherit' });
    pass('Build successful');
  } catch {
    fail('Build failed — fix errors and run npm run build');
  }

  // ── Step 6: Install background service ────────────────────

  console.log(`\n${BOLD}Step 6: Background service${RESET}\n`);
  const os = platform();

  if (os === 'darwin') {
    const installService = (await ask('Install launchd service? (y/n) [y]')).toLowerCase();
    if (installService !== 'n') {
      installLaunchd();
    } else {
      warn('Skipped launchd service installation');
    }
  } else if (os === 'linux') {
    const installService = (await ask('Install systemd user service? (y/n) [y]')).toLowerCase();
    if (installService !== 'n') {
      installSystemd();
    } else {
      warn('Skipped systemd service installation');
    }
  } else {
    warn(`Unsupported platform (${os}) for background service.`);
    console.log('  Use pm2 or run manually: npm start');
  }

  // ── Done ──────────────────────────────────────────────────

  console.log(`\n${BOLD}${GREEN}=== Setup Complete ===${RESET}\n`);
  console.log('Next steps:');
  if (!chatId) {
    console.log('  1. Start the bot: npm start');
    console.log('  2. Send /chatid to your Telegram bot');
    console.log('  3. Update ALLOWED_CHAT_ID in .env with your chat ID');
    console.log('  4. Restart the bot');
  } else {
    console.log('  1. Start the bot: npm start');
    console.log('  2. Send a message to your Telegram bot');
  }
  if (wantMatrix && !matrixToken) {
    console.log('  3. Run: npx tsx scripts/setup-matrix.ts');
  }
  console.log('\n  For voice features: docker compose -f docker/speaches.yml up -d');
  console.log('  For Docker mode: docker compose up -d');
  console.log('  Health check: npx tsx scripts/status.ts\n');

  rl.close();
}

function installLaunchd(): void {
  const plistName = 'com.luna.daemon';
  const plistPath = resolve(
    process.env.HOME || '~',
    'Library',
    'LaunchAgents',
    `${plistName}.plist`,
  );
  const nodePath = tryExec('which node') || '/usr/local/bin/node';
  const distIndex = resolve(PROJECT_ROOT, 'dist', 'index.js');
  const logPath = '/tmp/luna.log';

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${plistName}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodePath}</string>
    <string>${distIndex}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${PROJECT_ROOT}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>${logPath}</string>
  <key>StandardErrorPath</key>
  <string>${logPath}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
  </dict>
</dict>
</plist>`;

  writeFileSync(plistPath, plist);
  pass(`Wrote ${plistPath}`);

  try {
    tryExec(`launchctl unload "${plistPath}" 2>/dev/null`);
    execSync(`launchctl load "${plistPath}"`, { stdio: 'pipe' });
    pass('launchd service loaded (starts on login)');
  } catch {
    warn('Failed to load launchd service — load manually:');
    console.log(`    launchctl load "${plistPath}"`);
  }
}

function installSystemd(): void {
  const serviceDir = resolve(
    process.env.HOME || '~',
    '.config',
    'systemd',
    'user',
  );
  const servicePath = resolve(serviceDir, 'luna.service');
  const nodePath = tryExec('which node') || '/usr/bin/node';
  const distIndex = resolve(PROJECT_ROOT, 'dist', 'index.js');

  const unit = `[Unit]
Description=Luna — Personal AI Assistant Daemon
After=network.target

[Service]
Type=simple
ExecStart=${nodePath} ${distIndex}
WorkingDirectory=${PROJECT_ROOT}
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
`;

  try {
    execSync(`mkdir -p "${serviceDir}"`, { stdio: 'pipe' });
    writeFileSync(servicePath, unit);
    pass(`Wrote ${servicePath}`);

    execSync('systemctl --user daemon-reload', { stdio: 'pipe' });
    execSync('systemctl --user enable luna', { stdio: 'pipe' });
    pass('systemd service enabled (starts on login)');
    console.log('    Start now: systemctl --user start luna');
    console.log('    View logs: journalctl --user -u luna -f');
  } catch {
    warn('Failed to enable systemd service — enable manually:');
    console.log(`    systemctl --user enable luna`);
    console.log(`    systemctl --user start luna`);
  }
}

main().catch((err) => {
  console.error('Setup failed:', err);
  rl.close();
  process.exit(1);
});
